### ISSUE TITLE
Adminisztrátori chatek

### ISSUE THREAD

**Issue by SwannMorin** [AronDev/insiderpg-issues#3]
/as <- Adminsegéd chat megcsinálása (narancssárga szín esetleg) [ As, Modi, Adminok, VA, Tulaj, Fejlesztők ]
/mc <- Moderátor chat megcsinálása (citromsárga szín) [ Modik, Adminok, VA, Tulaj, Fejlesztők ]
/ac <- Admin chat megcsinálása (világos barna-sárga) [ Adminok, VA, Tulaj, Fejlesztők ]
/fc <- Fejlesztő chat megcsinálása (világos kék mint /asay szín) [ Va, Tulaj, Fejlesztők ]

**Comment by AronDev** [comment]
**/asc**, **/ac**, **/vac**, **/fc** hozzáadva
