### ISSUE TITLE
Beépített /elm javítása

### ISSUE THREAD

**Issue by SwannMorin** [AronDev/insiderpg-issues#5]
/elm <- parancs javítása, hogy működjön

**Comment by AronDev** [comment]
**/elm** hozzaadva

**Comment by AronDev** [comment]
_gamemodes/core/vehicles/callbacks.pwn_
`OnVehicleSpawn(vehicleid)`

A callback nem hívódik meg, így jármű respawn után az ELM nem áll meg.

**Comment by AronDev** [comment]
Befejezve.
